services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: santi
      POSTGRES_PASSWORD: santi_dev_password
      POSTGRES_DB: santi_toko
    ports:
      - "5432:5432"
    volumes:
      - santi_db_data:/var/lib/postgresql/data

volumes:
  santi_db_data:
